name: biumerch_mobile_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# ----------------- PACKAGES ---------------------#
dependencies:
  animated_splash_screen: ^1.3.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^5.1.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  file_picker: ^5.2.2
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fuzzy: ^0.5.1
  get: ^4.6.6
  google_sign_in: ^6.1.0
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^0.8.4+8
  intl: ^0.19.0
  mailer: ^6.1.2
  path: ^1.8.3
  permission_handler: ^10.2.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.0.0+4
  url_launcher: ^6.0.2

# -----------------./ PACKAGES END---------------------#
dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_shadow.png"

flutter:
  uses-material-design: true
  # ------------- LOCAL ASSETS ------------- #
  assets:
    - assets/logos/biumerch.png
    - assets/logos/biumerch_2.png
    - assets/logos/logo_baru.png
    - assets/images/background.jpg
    - assets/images/background.png
    - assets/images/SplashScreen.png
    - assets/images/
    - assets/images/ayam_geprek.png
    - assets/images/Resep_Chicken_Katsu.png
    - assets/images/esteh.jpeg
    - assets/images/senja.jpg
    - assets/images/img_binder_a5.png
    - assets/images/img_ayam_geprek_1.png
    - assets/images/img_resep_chicken_katsu.png
    - assets/images/filter.png
    - assets/images/saldo.jpg
    - assets/images/pesanan.jpg
    - assets/images/user.jpg
    - assets/images/esteh.jpeg
    - assets/images/geprek.png
    - assets/images/katsu.png
    - assets/images/senja.jpg
    - assets/icons/WA.jpg
    - assets/patternn1.png
    - assets/ic_outline-message.svg
    - assets/banners/banner1.png
    - assets/banners/
    - assets/icons/NavigationBar/beranda.svg
    - assets/icons/NavigationBar/kategori.svg
    - assets/icons/NavigationBar/keranjang.svg
    - assets/icons/NavigationBar/riwayat.png
    - assets/icons/NavigationBar/profil.svg
    - assets/icons/Kategori/jasa.svg
    - assets/icons/Kategori/makanan&minuman.svg
    - assets/icons/Kategori/lainnya.svg
    - assets/icons/Kategori/perlengkapan.svg
    - assets/banners/banner1.png
    - assets/banners/banner2.jpg
    - assets/banners/banner3.jpeg
    - assets/logo.png
    - assets/biumerch2.png
    - assets/BGLogin.png
    - assets/BGDaftar.png
    - assets/welcome.png
    - assets/google_logo.png
    - assets/verifikasilogo.png
    - assets/verfikasisukseslogo.png
    - assets/lupa_pw.png
  # ------------- LOCAL FONTS ------------- #
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
